# Generated by Django 4.0.5 on 2023-01-29 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Students',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=15)),
                ('middlename', models.CharField(max_length=15)),
                ('lastname', models.CharField(max_length=15)),
                ('Gender', models.CharField(choices=[('male', 'male'), ('female', 'female'), ('other', 'other')], default='male', max_length=7)),
                ('rollnumber', models.CharField(max_length=15)),
                ('phonenumber', models.IntegerField()),
                ('DateofBirth', models.DateField()),
                ('email', models.EmailField(max_length=254)),
                ('fathername', models.CharField(max_length=25)),
                ('mothername', models.CharField(max_length=25)),
                ('DateofAdmission', models.DateField()),
                ('Fees', models.CharField(choices=[('Reguar', 'Regular'), ('FullFee', 'Fullfee')], default='FullFees', max_length=10)),
            ],
        ),
    ]
