# Generated by Django 4.0.5 on 2023-01-30 14:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_student_delete_students'),
    ]

    operations = [
        migrations.CreateModel(
            name='Faculty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('facultyname', models.CharField(max_length=30)),
                ('Studentdetails', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student', to='base.student')),
            ],
        ),
    ]
