# Generated by Django 4.0.5 on 2023-03-14 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_faculty'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=15)),
                ('middlename', models.CharField(blank=True, max_length=15)),
                ('lastname', models.CharField(max_length=15)),
                ('Gender', models.CharField(choices=[('male', 'male'), ('female', 'female'), ('other', 'other')], default='male', max_length=7)),
                ('rollnumber', models.CharField(max_length=15)),
                ('phonenumber', models.CharField(max_length=11)),
                ('DateofBirth', models.CharField(max_length=12)),
                ('email', models.CharField(max_length=50)),
                ('fathername', models.CharField(max_length=25)),
                ('mothername', models.CharField(max_length=25)),
                ('DateofAdmission', models.CharField(max_length=12)),
                ('Fees', models.CharField(choices=[('Reguar', 'Regular'), ('FullFee', 'Fullfee')], default='FullFees', max_length=10)),
            ],
        ),
        migrations.DeleteModel(
            name='Faculty',
        ),
        migrations.DeleteModel(
            name='Student',
        ),
    ]
