# Generated by Django 4.0.5 on 2023-03-14 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_studentdetail_delete_faculty_delete_student'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentdetail',
            name='Fees',
            field=models.CharField(default='FullFees', max_length=10),
        ),
        migrations.AlterField(
            model_name='studentdetail',
            name='Gender',
            field=models.CharField(default='male', max_length=7),
        ),
        migrations.AlterField(
            model_name='studentdetail',
            name='middlename',
            field=models.CharField(max_length=15),
        ),
    ]
