# Generated by Django 4.0.5 on 2023-03-14 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_alter_studentdetail_fees_alter_studentdetail_gender_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentdetail',
            name='Fees',
            field=models.CharField(choices=[('Reguar', 'Regular'), ('FullFee', 'Fullfee')], default='FullFees', max_length=10),
        ),
        migrations.AlterField(
            model_name='studentdetail',
            name='Gender',
            field=models.CharField(choices=[('male', 'male'), ('female', 'female'), ('other', 'other')], default='male', max_length=7),
        ),
        migrations.AlterField(
            model_name='studentdetail',
            name='middlename',
            field=models.CharField(blank=True, max_length=15),
        ),
        migrations.AlterField(
            model_name='studentdetail',
            name='phonenumber',
            field=models.CharField(max_length=20),
        ),
    ]
